src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;


#[ORM\Entity(repositoryClass: ClubRepository::class)]
class Club
{


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @Groups({"club_list","club_details"})
     */
    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 4, minMessage: 'la longueur doit etre superieur a 4')]
    #[Assert\Regex(pattern: "/^[A-Za-z\s]+$/", message: "le nom ne peut contenir que des lettres et espaces.")]
    private ?string $nom = null;

    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $localisation = null;
    /**
     * @Groups({"club_list","club_details"})
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'id_club', targetEntity: Participation::class)]
    private Collection $participations;
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $type_activite = null;

    #[ORM\ManyToOne(inversedBy: 'clubs')]
    private ?User $id_clubOwner = null;
    /* message="Le numéro de téléphone doit être au format international et commencer par le code de pays (+XXX)."*/
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]

    #[Assert\Length(min: 10, minMessage: 'numero tres court')]
    #[Assert\Length(max: 15, maxMessage: 'longueur max dépassé')]
    #[Assert\Regex(pattern: "/^\+\d{1,3}\d{6,14}$/", message: "le numéro de telephone doit commencer par +XXX")]
    private ?string $telephone = null;
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Prix = null;

    #[ORM\Column]
    private ?float $longitude = null;

    #[ORM\Column]
    private ?float $latitude = null;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function getTypeActivite(): ?string
    {
        return $this->type_activite;
    }

    public function setTypeActivite(string $type_activite): self
    {
        $this->type_activite = $type_activite;

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): self
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setIdClub($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): self
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getIdClub() === $this) {
                $participation->setIdClub(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string)$this->getNom();
    }

    public function getIdClubOwner(): ?User
    {
        return $this->id_clubOwner;
    }

    public function setIdClubOwner(?User $id_clubOwner): self
    {
        $this->id_clubOwner = $id_clubOwner;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }
}

src/Entity/Participation.php
<?php

namespace App\Entity;

use App\Repository\ParticipationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;


#[ORM\Entity(repositoryClass: ParticipationRepository::class)]
class Participation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    /**
     * @Groups({"participation_list"})
     */
    #[ORM\ManyToOne(inversedBy: 'participations', cascade: ["persist"])]
    #[SerializedName("id_club")]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private ?Club $id_club = null;

    #[ORM\ManyToOne(inversedBy: 'participations')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private ?User $id_user = null;

    /**
     * @Groups({"participation_list"})
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $DateDebut = null;
    /**
     * @Groups({"participation_list"})
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $DateFin = null;

    #[ORM\Column]
    private ?bool $participated = null;

   




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClub(): ?Club
    {
        return $this->id_club;
    }



    public function setIdClub(?Club $id_club): self
    {
        $this->id_club = $id_club;

        return $this;
    }






    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }



    public function setDateDebut(?\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }


    public function date_to_string($date)
    {
        return $date->format('Y-m-d');
    }

    public function isParticipated(): ?bool
    {
        return $this->participated;
    }

    public function setParticipated(bool $participated): self
    {
        $this->participated = $participated;

        return $this;
    }

   
}

src/Form/ParticipationType.php
<?php

namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use App\Entity\Club;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Participation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints\IsTrue;


class ParticipationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_club', EntityType::class, array(
                'class' => Club::class,
                'choice_label' => 'nom',
            ))

            ->add('DateDebut', DateTimeType::class, [
                'widget' => 'single_text',
                'data' => new \DateTime(), // Remplir automatiquement le champ avec la date actuelle
                'empty_data' => new \DateTime(), // Utiliser la date actuelle si le champ est laissé vide
            ])
            ->add('DateFin', DateTimeType::class, [
                'widget' => 'single_text',
                'data' => (new \DateTime())->add(new \DateInterval('P1M')), // Remplir automatiquement le champ avec la date actuelle + 1 mois
                'empty_data' => (new \DateTime())->add(new \DateInterval('P1M')), // Utiliser la date actuelle + 1 mois si le champ est laissé vide
            ])



            /*
            ->add('accept_terms', CheckboxType::class, [
                'label' => 'J\'ai lu et j\'accepte les termes et conditions',
                'mapped' => false,
                'constraints' => new IsTrue([
                    'message' => 'Vous devez accepter les termes et conditions pour continuer.',
                ])])*/
            ->add("submit", SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Participation::class,
            'id_club' => null
        ]);
    }
}

src/Controller/ParticipationController.php
<?php

namespace App\Controller;

use App\Entity\Club;
use App\Repository\ClubRepository;
use App\Entity\Participation;
use App\Form\ParticipationType;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ParticipationRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ParticipationController extends AbstractController
{
    #[Route('/participation', name: 'app_participation')]
    public function index(): Response
    {
        return $this->render('participation/index.html.twig', [
            'controller_name' => 'ParticipationController',
        ]);
    }
    //read liste participation selon id du client
    #[Route('/client/listParticipation', name: 'list_participation')]
    public function listParticipation(ParticipationRepository $repository)
    {
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        $userId = $user->getId();
        $participations = $repository->findByIdClient($userId);
        // $clubs= $this->getDoctrine()->getRepository(ClubRepository::class)->findAll();
        return $this->render("participation/listParticipation.html.twig", array("tabParticipation" => $participations));
    }


    #[Route('/client/addParticipation/{id}', name: 'add_participation')]
    public function addParticipation($id, ParticipationRepository $repository, Request $request, ClubRepository $clubRepository)
    {
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        $club = $clubRepository->find($id);
        $existingParticipation = $repository->findActiveParticipation($user, $club);
        if ($existingParticipation !== null) {
            return $this->render('club/participated.html.twig');
        }
        $participation = new Participation();
        $participation->setIdClub($club);
        $participation->setParticipated(false);
        $prixClub = $clubRepository->findPrixClubById($club);
        $form = $this->createForm(ParticipationType::class, $participation);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $participation->setIdUser($user);
            $repository->add($participation, true);
            if ($participation->isParticipated() == true) {
                return $this->redirectToRoute("list_participation");
            } else {
                return $this->render("participation/waitPart.html.twig");
            }
        }
        return $this->renderForm("participation/addParticipation.html.twig", array("formParticipation" => $form, "prix" => $prixClub));
    }

    #[Route('/client/updateParticipation/{id}', name: 'update_participation')]
    public function  updateParticipation($id, ParticipationRepository $repository, ManagerRegistry $doctrine, Request $request)
    {
        $participation = $repository->find($id);
        $form = $this->createForm(ParticipationType::class, $participation);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $doctrine->getManager();
            $em->flush();
            return  $this->redirectToRoute("list_participation");
        }
        return $this->renderForm("participation/updateParticipation.html.twig", array("formParticipation" => $form));
    }
    #[Route('/client/removeParticipation/{id}', name: 'remove_participation')]

    public function removeParticipation(ManagerRegistry $doctrine, $id, ParticipationRepository $repository)
    {
        $participation = $repository->find($id);
        $em = $doctrine->getManager();
        $em->remove($participation);
        $em->flush();
        return  $this->redirectToRoute("list_participation");
    }
    /*
    #[Route('/listeAdherants', name: 'list_adherants')]
    public function listClientsByClubOwner(ParticipationRepository $participationRepository)
    {
        $clients = $participationRepository->findByIdClient(1);
        return $this->render('participation/listAdherantClub.html.twig', [
            'clients' => $clients,
        ]);
    }*/



    //////////////afficher la liste des clients qui ont participe aux clubs selon l id du club owner
    #[Route('/club/owner/ParticipationsAdherants', name: 'particip_adherants')]
    public function listParticipationsByClubOwner(ParticipationRepository $participationRepository)
    {
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        $userId = $user->getId();
        $participations = $participationRepository->findParticipationsByClubOwner($userId);
        return $this->render('participation/listAdherantClub.html.twig', [
            'participations' => $participations,
        ]);
    }
    ////////////////////////////////////////////remove participation client par clubowner

    #[Route('/club/owner/removeParticipations/{id}', name: 'remove_participationClient')]

    public function removeParticipation1(ManagerRegistry $doctrine, $id, ParticipationRepository $repository)
    {
        $participation = $repository->find($id);
        $em = $doctrine->getManager();
        $em->remove($participation);
        $em->flush();
        return  $this->redirectToRoute("particip_adherants");
    }

    /////////////////////////////////////////////client is participated approve
    #[Route('/club/owner/isParticipared/{id}', name: 'isParticipated_participationClient')]
    public function participated(Request $request, ParticipationRepository $participationRepository, int $id)
    {
        $participation = $participationRepository->find($id);

        $participation->setParticipated(true);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($participation);
        $entityManager->flush();

        $this->addFlash('success', 'client is now participated!');

        return $this->redirectToRoute('particip_adherants');
    }
    /////////////////////////////

}

templates/participation/addParticipation.html.twig
{% extends 'base-front.html.twig'%}
{% block body %}

<div class="breadcrumb-section breadcrumb-bg" >
    <div class="container">
        <div class="row">
             <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Join Bour la forme to make your life easier</p>
                    <h1>Participer</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="body">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="container shadow p-3 mb-5 bg-white rounded mx-auto">
            
                <h3><center><mark>Ajouter Participation</center></mark></h3>
                {{ form_start(formParticipation) }}
                {{ form_row(formParticipation.id_club) }}
                {{ form_row(formParticipation.DateDebut) }}
                {{ form_row(formParticipation.DateFin)  }}
                <div> le prix de l'abonnement est : {{prix}} </div>
                {{ form_end(formParticipation) }}

        </div>      
    </div>
</div>
{% endblock %}

templates/participation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ParticipationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/obba/OneDrive/Documents/GitHub/Projet_Anarchy/src/Controller/ParticipationController.php'|file_link(0) }}">src/Controller/ParticipationController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/obba/OneDrive/Documents/GitHub/Projet_Anarchy/templates/participation/index.html.twig'|file_link(0) }}">templates/participation/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/participation/listAdherantClub.html.twig
{% extends 'base-back.html.twig' %}
{% block sidenav %} 

    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon">
                        <i class="fas fa-columns"></i>
                 </div>
                Clubs
                <div class="sb-sidenav-collapse-arrow">
                        <i class="fas fa-angle-down"></i>
                </div>
        </a>
        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{path('add_club')}}">Ajouter un Club</a>
                         <a class="nav-link" href="{{path('list_club')}}">Liste des clubs</a>
                </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon">
                        <i class="fas fa-columns"></i>
                 </div>
                Participations
                <div class="sb-sidenav-collapse-arrow">
                        <i class="fas fa-angle-down"></i>
                </div>
        </a>
        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{path('particip_adherants')}}"> Liste des Adhérants</a>
                        
                </nav>
        </div>

{% endblock %}
{% block body %}
    <h2><center><mark>Liste des Adhérants</mark></center></h2>
    <div class="container mt-5">
        <div class="table-responsive">
            <table class="table table-striped  table-hover">
                <thead>
                    <tr>
                        <th>Nom Club</th>
                        <th>Nom Adhérant</th>
                        <th>Email</th>
                        <th>Téléphone</th>
                        <th>Actions</th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for parti in participations %}
                        <tr>
                            <td>{{ parti.getIdClub() }}</td>
                            <td>{{ parti.getIdUser().getNom() }}</td>
                            <td>{{ parti.getIdUser().getUsername() }}</td>
                            <td>{{ parti.getIdUser().getPrenom() }}</td>
                            <td>
                                <a href="{{ path('remove_participationClient', {'id': parti.id}) }}"><i class="fas fa-trash text-danger"></i></a>
                            
                                {% if not parti.participated %}
                                    <a href="{{ path('isParticipated_participationClient', {'id': parti.id}) }}"><i  class="fa-regular fa-circle-check"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="3">Aucun client trouvé.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/participation/listParticipation.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Mes Clubs{% endblock %}
{#
{% block css %}
<div class="bg-image" style="background-image: src="{{asset('uploads/brochures/gym3.jpg')}}""></div>
{% endblock %}#}
{% block body %}



<div class="breadcrumb-section breadcrumb-bg" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <p>Join Bour la forme to make your life easier</p>
                        <h1>Mes Clubs</h1>
                    </div>
                </div>
            </div>
        </div>
</div>

<div class="container mt-5">
    
    <div class="table-responsive">
        <table class="table table-striped  table-hover">
            <thead>
                    <tr>
                        <th><mark> Nom Club</mark></th>
                        <th><mark>Date début participation</mark></th>
                        <th><mark>Date Fin participation</mark></th>
                        <th><mark>Actions</mark></th>
                      
                    </tr>
            </thead>
            <tbody>
                {% for i in  tabParticipation %}

                    <tr>
                        <td>{{i.getIdClub()}} </td>
                            
                        <td class="font-weight-bold">{{i.DateDebut|date('d/m/Y')}} </td>
                        <td class="font-weight-bold">{{i.DateFin|date('d/m/Y ')}}   </td>
                        <td>
                            <a href= "{{ path('remove_participation',{'id':i.id}) }}"><i class="fas fa-trash text-danger"></i></a>
                            <a href= "{{ path('update_participation',{'id':i.id}) }}"><i class="fas fa-edit text-primary"></i></a> 
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
   

templates/participation/mesClubs.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Mes clubs{% endblock %}
<a href="{{ path('club_index') }}">+Ajouter participation</a>
{% block body %}
    <h1>Mes clubs</h1>

    {% if clubs is empty %}
        <p>Vous n'êtes inscrit dans aucun club pour le moment.</p>
    {% else %}
        <table>
            <thead>
                <tr>
                    <th>Club</th>
                    <th>Date de participation</th>
                </tr>
            </thead>
            <tbody>
                {% for mc in mes_clubs %}
                    <tr>
                        <td>{{ mc.name }}</td>
                        <td><img src="{{ asset('uploads/brochures'~ mc.image) }}" alt="{{ mc.name }}" height="100"></td>
                        <td>{{ mc.description }}</td>
                        <td>{{ mc.activityType }}</td>
                        <td>{{ mc.dateDebut|date('Y-m-d') }}</td>
                        <td>{{ mc.dateFin|date('Y-m-d') }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/participation/updateParticipation.html.twig
{% extends 'base-front.html.twig'%}
{% block body %}

<div class="breadcrumb-section breadcrumb-bg" >
    <div class="container">
        <div class="row">
             <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Join Bour la forme to make your life easier</p>
                    <h1>Modifier Votre Participation</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="body">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="container shadow p-3 mb-5 bg-white rounded mx-auto">
            <div class="container">
            <h3><mark><center>Editer La Participation<center></mark></h3>
            {{ form(formParticipation) }}
            <form action="" method="">
            </form>
        </div>      
    </div>
    <a href="{{ path('club_index') }}" class="btn btn-primary">Annuler Modifications</a>

</div>
{% endblock %}

templates/participation/waitPart.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}details du club{% endblock %}


{% block body %}
    <div class="breadcrumb-section breadcrumb-bg" >
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2 text-center">
                        <div class="breadcrumb-text">
                            <p>Join Bour la forme to make your life easier</p>
                            <h1>Attente de confirmation</h1>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    
    <div class="single-product mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-md-5">

                        <h4>Veuillez attendre l'acceptation de votre participation</h4>
                        <p>Vous pouvez consulter la liste de nos clubs disponible pendant votre attente </p>
                        <a href="{{ path('club_index') }}" class="cart-btn">Consulter</a>


                </div>
            </div>   

        </div>
    </div>



{% endblock %}