src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;


#[ORM\Entity(repositoryClass: ClubRepository::class)]
class Club
{


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @Groups({"club_list","club_details"})
     */
    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 4, minMessage: 'la longueur doit etre superieur a 4')]
    #[Assert\Regex(pattern: "/^[A-Za-z\s]+$/", message: "le nom ne peut contenir que des lettres et espaces.")]
    private ?string $nom = null;

    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $localisation = null;
    /**
     * @Groups({"club_list","club_details"})
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'id_club', targetEntity: Participation::class)]
    private Collection $participations;
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $type_activite = null;

    #[ORM\ManyToOne(inversedBy: 'clubs')]
    private ?User $id_clubOwner = null;
    /* message="Le numéro de téléphone doit être au format international et commencer par le code de pays (+XXX)."*/
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]

    #[Assert\Length(min: 10, minMessage: 'numero tres court')]
    #[Assert\Length(max: 15, maxMessage: 'longueur max dépassé')]
    #[Assert\Regex(pattern: "/^\+\d{1,3}\d{6,14}$/", message: "le numéro de telephone doit commencer par +XXX")]
    private ?string $telephone = null;
    /**
     * @Groups({"club_list"})
     */
    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Prix = null;

    #[ORM\Column]
    private ?float $longitude = null;

    #[ORM\Column]
    private ?float $latitude = null;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function getTypeActivite(): ?string
    {
        return $this->type_activite;
    }

    public function setTypeActivite(string $type_activite): self
    {
        $this->type_activite = $type_activite;

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): self
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setIdClub($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): self
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getIdClub() === $this) {
                $participation->setIdClub(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string)$this->getNom();
    }

    public function getIdClubOwner(): ?User
    {
        return $this->id_clubOwner;
    }

    public function setIdClubOwner(?User $id_clubOwner): self
    {
        $this->id_clubOwner = $id_clubOwner;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }
}

src/Controller/CheckoutController.php
<?php

namespace App\Controller;
use App\Entity\BillingAddress;
use App\Form\BillingAddressType;
use App\Repository\BillingAddressRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface ;
use App\Repository\ArticleRepository;
use App\Entity\Panier;
use App\Entity\PanierArticle;
use App\Entity\Article;
use App\Entity\Commande;
use DateTime;


class CheckoutController extends AbstractController
{
    /**
     * @Route("/client/checkout", name="checkout")
     */
    public function index(): Response
    {

        return $this->render('checkout/index.html.twig', [
            'controller_name' => 'CheckoutController',
        ]);
    }
        /**
     * @Route("/client/checkout2", name="checkout2")
     */
    public function index2(SessionInterface $session , ArticleRepository $ArticleRepository): Response
    {
            $panier = $session->get('panier', []); 
    
            $panierWithData = []; 
    
            foreach ($panier as $id => $quantity) {
    
             $panierWithData[] = ['Article' => $ArticleRepository->find($id) , 'quantity' => $quantity ];
        }
            $total=0 ;
            foreach ($panierWithData as $item )
                {
                $totalItem= $item['Article']->getPrix()*$item['quantity'];
                 $total += $totalItem;
                }  
                
    
                return $this->render('checkout/index2.html.twig', [
                    'items' => $panierWithData,
                    'total'=>$total
                ]);
        }    
            /**
     * @Route("/client/checkout3", name="checkout3")
     */
    public function index3(): Response
    {
        return $this->render('checkout/placeOrder.html.twig');
    }
                /**
     * @Route("/client/checkout4", name="checkout4")
     */
    public function index4(): Response
    {
        return $this->render('checkout/fail.html.twig');
    }
    #[Route('/addFormBA', name: 'addBA')]
    public function addForm(ManagerRegistry $doctrine,Request $request)
    {
        $BillingAddress= new BillingAddress();
        $form= $this->createForm(BillingAddressType::class,$BillingAddress);
        $form->handleRequest($request) ;
        if ($form->isSubmitted()&& $form->isValid()){
            $em= $doctrine->getManager();
            $em->persist($BillingAddress);
            $em->flush();
            return $this->redirectToRoute("checkout2");
         }
        return $this->renderForm("checkout/add.html.twig",array("formBillingAddress"=>$form));
    }
    #[Route('/client/PlaceOrder', name: 'placeOrder')]
    public function PlaceOrder(SessionInterface $session , ArticleRepository $ArticleRepository,ManagerRegistry $doctrine,Request $request):response
    {
                
        $pan = $session->get('panier', []); 

        $panierWithData = []; 
        $panier=new Panier();
        $panier->setPrix(100);
        $panier->setQuantity(2);
        $panier->setConfirme(true);
        $a= $doctrine->getManager();
        $a->persist($panier);
        $a->flush();
        $em= $doctrine->getManager();
        foreach ($pan as $id => $quantity) {
         
         $panierWithData[] = ['Article' => $ArticleRepository->find($id) , 'quantity' => $quantity ];
         $panierArticle= new PanierArticle();
         $panierArticle->setIdArticle($ArticleRepository->find($id));
         $panierArticle->setQuantity($quantity);
         $panierArticle->setIdPanier($panier);
         $em->persist($panierArticle);
            }
            $em->flush();
        $quantity=0;
        $total=0 ;
        foreach ($panierWithData as $item )
            {
            $totalItem= $item['Article']->getPrix()*$item['quantity'];
             $total += $totalItem;
             $quantity=$quantity+1;

            }  
            $panier->setPrix($total);
            $panier->setQuantity($quantity);
            $panier->setConfirme(true);
            $a= $doctrine->getManager();
            $a->persist($panier);
            $a->flush();
            $date = new DateTime();
            $repository = $this->getDoctrine()->getRepository(BillingAddress::class);

            $derniereLigne = $repository->findOneBy([], ['id' => 'desc']);
            $commande=new Commande ();
            $commande->setMontant($total);
            $commande->setIdPanier($panier);
            $commande->setIdAddress($derniereLigne);
            $commande->setDate($date );
            $commande->setConfirmeAdmin(false);
            $c= $doctrine->getManager();
            $c->persist($commande);
            $c->flush();
            $session->remove('panier');
            return $this->render('checkout/final.html.twig');
        }

    }

 

templates/checkout/add.html.twig
{% extends 'base-front.html.twig' %}
{% block body %}
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Billing Address</p>
						<h1>You Must Fill Out This Form To Go To The Next Step</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
      <div class="container">  
        <div class="row justify-content-center">  
            <div class="col-11 col-sm-9 col-md-7  
                col-lg-6 col-xl-5 text-center p-0 mt-3 mb-2">  
                <div class="px-0 pt-4 pb-0 mt-3 mb-3">  
                    <form id="form">  
                    <ul id="progressbar">  
                    <li class="active" id="step1">  
                    <strong> Review Order </strong>  
                    <li class="active" id="step2">  
                    <strong> Adress </strong>  
                    </li>  
                    </li>  
                    <li id="step3"> <strong> Payment </strong> </li>  
                    <li id="step4"> <strong> Place Order </strong> </li>  
                        </ul>  
                    </form>  
                </div>  
            </div>  
        </div>  
    </div>  

<h2>Billing Address</h2>
 						      <div class="card-body"style="margin-left:10%;">
                        
  {{ form_start(formBillingAddress, {'attr': { 'novalidate': 'novalidate'} }) }}
            {{form_row(formBillingAddress)}}

    {{ form_end(formBillingAddress) }}
                                    </div>

  {% endblock %}





      

templates/checkout/fail.html.twig
{% extends 'base-front.html.twig' %}


{% block body %}
<div class="breadcrumb-section breadcrumb-bg" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <p> Votre paiement a été rejeté !</p>
                        <h1><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></h1>
                    </div>
                <h4> Vous avez essayé de payer votre commande et nous vous en remercions.
                                Votre paiement n'a pas été accepté. Votre commande n'a pas été confirmée.
                                Nous vous invitons à vérifier la validation de votre carte bancaire, et à vous connecter sur notre site et renouveller votre commande.</h4>

            <a href="{{ path('list_article2')}}" class="boxed-btn">Start Shopping</a>
            <br>
                </div>
            </div>
        </div>
 
{% endblock %}

templates/checkout/final.html.twig
{% extends 'base-front.html.twig' %}


{% block body %}
<div class="breadcrumb-section breadcrumb-bg" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <p>Checkout Done</p>
                        <h1><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></h1>
                    </div>
                <h4> your order has been confirmed</h4>

            <a href="{{ path('list_article2')}}" class="boxed-btn">Start Shopping</a>
            <br>
                </div>
            </div>
        </div>
 
{% endblock %}

templates/checkout/index.html.twig
 
 {% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Check Out</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="assets/img/favicon.png">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="assets/css/all.min.css">
	<!-- bootstrap -->
	<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
	<!-- owl carousel -->
	<link rel="stylesheet" href="assets/css/owl.carousel.css">
	<!-- magnific popup -->
	<link rel="stylesheet" href="assets/css/magnific-popup.css">
	<!-- animate css -->
	<link rel="stylesheet" href="assets/css/animate.css">
	<!-- mean menu css -->
	<link rel="stylesheet" href="assets/css/meanmenu.min.css">
	<!-- main style -->
	<link rel="stylesheet" href="assets/css/main.css">
	<!-- responsive -->
	<link rel="stylesheet" href="assets/css/responsive.css">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="index.html">
								<img src="assets/img/logo.png" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="#">Home</a>
									<ul class="sub-menu">
										<li><a href="index.html">Static Home</a></li>
										<li><a href="index_2.html">Slider Home</a></li>
									</ul>
								</li>
								<li><a href="about.html">About</a></li>
								<li><a href="#">Pages</a>
									<ul class="sub-menu">
										<li><a href="404.html">404 page</a></li>
										<li><a href="about.html">About</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="contact.html">Contact</a></li>
										<li><a href="news.html">News</a></li>
										<li><a href="shop.html">Shop</a></li>
									</ul>
								</li>
								<li><a href="news.html">News</a>
									<ul class="sub-menu">
										<li><a href="news.html">News</a></li>
										<li><a href="single-news.html">Single News</a></li>
									</ul>
								</li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="shop.html">Shop</a>
									<ul class="sub-menu">
										<li><a href="shop.html">Shop</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="single-product.html">Single Product</a></li>
										<li><a href="cart.html">Cart</a></li>
									</ul>
								</li>
								<li>
									<div class="header-icons">
										<a class="shopping-cart" href="cart.html"><i class="fas fa-shopping-cart"></i></a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Place Order</p>
						<h1> </h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- check out section -->
	<div class="checkout-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="checkout-accordion-wrap">
						<div class="accordion" id="accordionExample">
						  <div class="card single-accordion">
						    <div class="card-header" id="headingOne">
						      <h5 class="mb-0">
						        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									<a class="nav-link" href="{{ path('addBA') }}">						          Billing Address
</a>
						        </button>
						      </h5>
						    </div>
						  </div>
						  <div class="card single-accordion">
						    <div class="card-header" id="headingThree">
						      <h5 class="mb-0">
						        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
						          Card Details
						        </button>
						      </h5>
						    </div>
						    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
						      <div class="card-body">
						        <div class="card-details">
						        	<p>Your card details goes here.</p>
						        </div>
						      </div>
						    </div>
						  </div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end check out section -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="assets/img/company-logos/1.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/2.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/3.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/4.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/5.png" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	<script src="assets/js/jquery-1.11.3.min.js"></script>
	<!-- bootstrap -->
	<script src="assets/bootstrap/js/bootstrap.min.js"></script>
	<!-- count down -->
	<script src="assets/js/jquery.countdown.js"></script>
	<!-- isotope -->
	<script src="assets/js/jquery.isotope-3.0.6.min.js"></script>
	<!-- waypoints -->
	<script src="assets/js/waypoints.js"></script>
	<!-- owl carousel -->
	<script src="assets/js/owl.carousel.min.js"></script>
	<!-- magnific popup -->
	<script src="assets/js/jquery.magnific-popup.min.js"></script>
	<!-- mean menu -->
	<script src="assets/js/jquery.meanmenu.min.js"></script>
	<!-- sticker js -->
	<script src="assets/js/sticker.js"></script>
	<!-- main js -->
	<script src="assets/js/main.js"></script>

</body>
</html>
{% endblock %}

templates/checkout/index2.html.twig
{% extends 'base-front.html.twig' %}
{% block body %}
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Payment</p>
						<h1>MONEY</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
      <div class="container">  
        <div class="row justify-content-center">  
            <div class="col-11 col-sm-9 col-md-7  
                col-lg-6 col-xl-5 text-center p-0 mt-3 mb-2">  
                <div class="px-0 pt-4 pb-0 mt-3 mb-3">  
                    <form id="form">  
                    <ul id="progressbar">  
                    <li class="active" id="step1">  
                    <strong> Review Order </strong>  
                    <li class="active" id="step2">  
                    <strong> Adress </strong>  
                    </li>  
                    </li>  
                    <li class="active" id="step3">  
                    <strong> Payment </strong>  
                    </li>  
                    <li id="step4"> <strong> Place Order </strong> </li>  
                        </ul>  
                    </form>  
                </div>  
            </div>  
        </div>  
    </div>  

					<div class="col-lg-4">
                    <table class="order-details">
							<thead>
								<tr>
									<th>Name</th>
									<th>Price</th>
                                    <th>Quantity</th>
								</tr>
							</thead>
							<tbody class="order-details-body">
                                {% for item in items %}
								<tr class="table-body-row">
									<td>{{item.Article.nom}}</td>
									<td class="product-price">{{item.Article.prix}}DT</td>
									<td class="product-quantity"> {{item.quantity}}</td>           
								</tr>

                                {% endfor %}
                                </table>
					<div class="order-details-wrap" style="margin-left:150%;" >
						<a href="{{ path('app_stripe') }}" class="boxed-btn">Payer {{total}}DT </a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/checkout/placeOrder.html.twig
{% extends 'base-front.html.twig' %}
{% block body %}
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Place Order </p>
						<h1>Payment Successful </h1>
					</div>
				</div>
			</div>
		</div>
	</div>
      <div class="container">  
        <div class="row justify-content-center">  
            <div class="col-11 col-sm-9 col-md-7  
                col-lg-6 col-xl-5 text-center p-0 mt-3 mb-2">  
                <div class="px-0 pt-4 pb-0 mt-3 mb-3">  
                    <form id="form">  
                    <ul id="progressbar">  
                    <li class="active" id="step1">  
                    <strong> Review Order </strong>  
                    <li class="active" id="step2">  
                    <strong> Adress </strong>  
                    </li>  
                    </li>  
                    <li class="active" id="step3">  
                    <strong> Payment </strong>  
                    </li>  
                    <li class="active" id="step4">  
                    <strong> Place Order </strong>  
                    </li>  
                        </ul>  
                    </form>  
                </div>  
            </div>  
        </div>  
    </div>  
					<div class="col-lg-4">
					<div class="order-details-wrap" style="margin-left:150%;" >
						<a href="{{ path('placeOrder') }}" class="boxed-btn">Place Order</a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}